### ISSUE TITLE
[ENHANCEMENT] Change Links to relative links

### ISSUE THREAD

**Issue by sumodirjo** [traveloka/terraform-aws-modules-template#19]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* ***If you have submitted a pull request addressing the same issue, please leave a comment!***

***

### Description

We have links in the template that using absolute path / URL path. When using this repository as template, users have to change the URL to their repository URL.

By changing url to relative URL users doesn't have to do additional tasks when using this repository as template.

### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration Changes

```hcl
# Copy-paste your Terraform configurations here.
# For large Terraform configs, please use a service like Google Drive and share a link to the ZIP file.
```

### References

* https://help.github.com/en/articles/about-readmes

**Comment by rafikurnia** [comment]
Thanks for the issue. Indeed it will reduce our effort when using this repo as template.

**Comment by rafikurnia** [comment]
Hi @sumodirjo 
After re visit the templates, I found that relative link implementation is not possible.
Because we have link on the PR template and CONTRIBUTING.md file which is not pointing to another file.
